services:
  backend:
    image: crpi-yvha9coypdedaafa.cn-beijing.personal.cr.aliyuncs.com/lys1313013/aio-life-server:latest
    container_name: aio-life-server
    restart: unless-stopped
    ports:
      - "45678:45678"
      - "45679:45679"
    env_file:
      - .env
    networks:
      - aio-life

  frontend:
    image: crpi-yvha9coypdedaafa.cn-beijing.personal.cr.aliyuncs.com/lys1313013/aio-life-front:latest
    container_name: aio-life-front
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - aio-life

networks:
  aio-life:
    name: aio-life
